//Object holding all possible Video Game phrases
module.exports = {
array: [      
    "Pong",	
    "Zork",	
    "Space Invaders",	
    "Asteroids",
    "Adventure",	
    "Pac Man",
    "Defender",	
    "Donkey Kong",	
    "Galaga",	
    "Joust",	
    "Ms Pac Man",	
    "Pitfall",
    "Punch Out",
    "Star Wars",	
    "Elite",	
    "Tetris",	
    "Gauntlet",	
    "Super Mario Bros",	
    "The Legend of Zelda",	
    "Out Run",	
    "Contra",	
    "Double Dragon",	
    "Tecmo Bowl",	
    "Mega Man II",
    "Ninja Gaiden",	
    "Super Mario Bros III",
    "Prince of Persia",	
    "SimCity",
    "The Secret of Monkey Island",	
    "Super Mario World",	
    "The Legend of Zelda A Link to the Past",	
    "Lemmings",	
    "Sonic the Hedgehog",	
    "Street Fighter",	
    "Mortal Kombat",	
    "Super Mario Kart",	
    "Wolfenstein", 
    "Day of the Tentacle",	
    "Daytona USA",	
    "Doom",	
    "Gunstar Heroes",	
    "The Legend of Zelda Links Awakening",	
    "Mega Man X",	
    "Myst",	
    "NBA Jam",	
    "Phantasy Star", 
    "Sam And Max Hit the Road",
    "Secret of Mana",	
    "SimCity", 
    "Donkey Kong Country",	
    "EarthBound",	
    "Final Fantasy", 
    "Star Wars TIE Fighter",	
    "Super Metroid",	
    "UFO Enemy Unknown",	
    "Chrono Trigger",	
    "Command And Conquer",	
    "Warcraft", 
    "Wipeout",	
    "Yoshis Island",	
    "Civilization II",	
    "Command And Conquer Red Alert",	
    "Nights into Dreams",
    "Pokémon Red and Blue",	
    "Quake",	
    "Resident Evil",	
    "Super Mario RPG",	
    "Tomb Raider",	
    "Castlevania Symphony of the Night",	
    "Fallout",
    "Final Fantasy Tactics",	
    "Final Fantasy VII",	
    "GoldenEye", 
    "Gran Turismo",	
    "Quake II",
    "Star Fox", 
    "Star Wars Jedi Knight Dark Forces II",	
    "Tekken III",	
    "Ultima Online",	
    "Grim Fandango",	
    "Half Life",	
    "The Legend of Zelda Ocarina of Time",	
    "Metal Gear Solid",	
    "Panzer Dragoon Saga",	
    "Resident Evil II",
    "SoulCalibur",	
    "StarCraft",	
    "Thief The Dark Project",	
    "Age of Empires II The Age of Kings",	
    "EverQuest",	
    "Homeworld",	
    "Planescape Torment",	
    "Shenmue",	
    "Silent Hill",	
    "Super Smash Bros",
    "System Shock II",
    "Unreal Tournament",	
    "Counter Strike",	
    "Deus Ex",
    "Diablo II",
    "Jet Set Radio",	
    "The Legend of Zelda Majoras Mask",	
    "The Sims",
    "Thief II The Metal Age",	
    "Tony Hawks Pro Skater II",
    "Advance Wars",
    "Final Fantasy X",	
    "Gran Turismo III A Spec",	
    "Grand Theft Auto III",
    "Halo Combat Evolved",
    "Ico",
    "Ikaruga",
    "Max Payne",
    "Metal Gear Solid II Sons of Liberty",	
    "Phoenix Wright Ace Attorney",	
    "Rez",
    "Silent Hill II",
    "Super Smash Bros Melee",	
    "Grand Theft Auto Vice City",	
    "The Legend of Zelda The Wind Waker",
    "Metroid Prime",	
    "Prince of Persia The Sands of Time",	
    "Star Wars Knights of the Old Republic",	
    "Burnout III Takedown",	
    "Grand Theft Auto San Andreas",	
    "Half Life II",
    "Katamari Damacy",	
    "Metal Gear Solid III Snake Eater",	
    "World of Warcraft",	
    "Civilization IV",	
    "Devil May Cry III Dantes Awakening",
    "God of War",
    "Guitar Hero",	
    "Psychonauts",
    "Resident Evil IV",
    "Shadow of the Colossus",
    "The Elder Scrolls IV Oblivion",
    "Gears of War",
    "Ōkami",
    "Wii Sports",
    "BioShock",
    "God of War II",
    "Halo III",
    "Portal",	
    "Super Mario Galaxy",
    "Team Fortress II",
    "Braid",	
    "Dead Space",	
    "Fallout III",
    "Grand Theft Auto IV",	
    "LittleBigPlanet",	
    "Metal Gear Solid IV Guns of the Patriots",	
    "Shin Megami Tensei Persona IV",	
    "Spelunky",
    "Street Fighter IV",	
    "Assassins Creed II",
    "Batman Arkham Asylum",	
    "Uncharted II Among Thieves",
    "Limbo",
    "Mass Effect II",
    "Red Dead Redemption",	
    "Rock Band", 
    "Super Mario Galaxy II",
    "Super Meat Boy",
    "Batman Arkham City",	
    "Dark Souls",
    "The Elder Scrolls V Skyrim",	
    "Minecraft",	
    "Portal II",
    "Fire Emblem Awakening",	
    "Hotline Miami",
    "Journey",
    "Mass Effect III",
    "The Walking Dead",
    "Dota II",
    "Grand Theft Auto V",	
    "The Last of Us",
    "TowerFall",	
    "Bloodborne",	
    "The Witcher III Wild Hunt"]
}
